baseURL = "/"
title = "Pabpereza - DevSecOps"

enableRobotsTXT = true


# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["github.com/google/docsy", "github.com/google/docsy/dependencies"]

# Will give values to .Lastmod etc.
enableGitInfo = true

# Language settings
contentDir = "content/es"
defaultContentLanguage = "es"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true


# Taxonomies
[taxonomies]
tag = "tags"
categories = "categories"

[params.taxonomy]
taxonomyCloud = ["tags","categories"] # set taxonomyCloud = [] to hide taxonomy clouds
taxonomyCloudTitle = ["Etiquetas","Categorías"] # if used, must have same lang as taxonomyCloud


# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"


[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
# id = "G-40PL0BKGD3"

# Language configuration

[languages]
[languages.es]
title = ""
description = "Blog, documentación y vídeos"
languageName ="Español"
# Weight used for sorting.
weight = 1



# Everything below this are Site Params

# Comment out if you don't want the "print entire section" link enabled.
[outputs]
section = ["HTML", "print","RSS"]

[params]
copyright = "Docsy Authors"
privacy_policy = "https://policies.google.com/privacy"


# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Releases"


# Flag used in the "version-banner" partial to decide whether to display a 
# banner on every page indicating that this is an archived version of the docs.
# Set this flag to "true" if you want to display the banner.
archived_version = false

# The version number for the version of the docs represented in this doc set.
# Used in the "version-banner" partial to display a version number for the 
# current doc set.
version = "0.0"

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
url_latest_version = "https://example.com"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/pabpereza/pabpereza"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/pabpereza/pabpereza"

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = ""

# Uncomment this if you have a newer GitHub repo with "main" as the default branch,
# or specify a new value if you want to reference another branch in your GitHub links
github_branch= "main"

# Google Custom Search Engine ID. Remove or comment out to disable search.
#gcs_engine_id = "d72aa9b2712488cc3"

# Enable Algolia DocSearch
#algolia_docsearch = true 

# Enable Lunr.js offline search
offlineSearch = true



# Enable Emojis
enableEmoji = true

[markup.goldmark.renderer]
unsafe= true



# Additional menu items
[[menu.main]]
  name = "Sobre mí"
  weight = "10"
  url = "/#about"
  pre = "<i class='fas fa-user'></i>"

[[menu.main]]
  name = "Documentación"
  weight = "20"
  url = "/docs/"
  pre = "<i class='fas fa-book'></i>"

[[menu.main]]
  name = "Blog"
  weight = "30"
  url = "/blog/"
  pre = "<i class='fas fa-blog'></i>"

[[menu.main]]
  name = "Vídeos"
  weight = "100"
  url = "https://www.youtube.com/channel/UCGfKISiN7usAdxvcGivm_OA/featured"
  pre = "<i class='fab fa-youtube'></i>"

[[menu.main]]
  name = " "
  weight = "110"
  url = "https://twitter.com/pabpereza"
  pre = "<i class='fab fa-twitter'></i>"

[[menu.main]]
  name = ""
  weight = "120"
  url = "https://github.com/pabpereza/pabpereza"
  pre = "<i class='fab fa-github'></i>"

 

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true 
ul_show = 2
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false 
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = true 




# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true 

# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = '¡Me alegra escucharlo!. Por favor, <a href="https://github.com/pabpereza/pabpereza/issues/new">ayudanos a mejorar</a>.'
no = 'Siento oírlo. Por favor, <a href="https://github.com/pabpereza/pabpereza/issues/new">ayudanos a mejorar</a>.'

# Activate markmap
[params.markmap]
enable = true

# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page, 
# add "hide_readingtime: true" to the page's front matter
[params.ui.readingtime]
enable = true 

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
	name = "Perfil profesional en linkedin"
	url = "https://www.linkedin.com/in/pablo-pérez-aradros-calvo-516634109/"
	icon = "fab fa-linkedin"
        desc = "Sígueme para las últimas novedades"
[[params.links.user]]
	name ="Twitter"
	url = "https://twitter.com/pabpereza"
	icon = "fab fa-twitter"
        desc = "Sígueme para las últimas novedades"
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/pabpereza/pabpereza"
	icon = "fab fa-github"
        desc = "Aquí es donde se desarrolla"
[[params.links.developer]]
	name = "Correo personal"
	url = "mailto:pabloperezaradros@gmail.com"
	icon = "fa fa-envelope"
        desc = "Envíame un email"

